use nalgebra::{Vector3, Vector4, Quaternion};
use std::net::Ipv4Addr as IpAddr;

type IpPort = u16;
type LLUUID = u16;

// Don't edit this file manually, it is generated by a script and might be overwritten in the
// future.

